"""
Interest-rate exposure simulation.

This module revalues vanilla swaps along simulated
forward-rate paths generated by the Gaussian LMM or
the LMM-SABR hybrid model.
"""

import numpy as np

from xva_trade import (
    InterestRateSwap,
    NettingSet
)


class ExposureSimulationResult:
    """
    Container for future trade and portfolio values.
    """

    def __init__(
        self,
        exposure_times,
        trade_ids,
        trade_values,
        portfolio_values
    ):
        self.exposure_times = np.asarray(
            exposure_times,
            dtype=float
        )

        self.trade_ids = list(
            trade_ids
        )

        self.trade_values = np.asarray(
            trade_values,
            dtype=float
        )

        self.portfolio_values = np.asarray(
            portfolio_values,
            dtype=float
        )

        self.validate()

    def validate(
        self
    ):
        """
        Validate result dimensions.
        """

        if self.trade_values.ndim != 3:
            raise ValueError(
                "trade_values must have dimensions "
                "[path, time, trade]."
            )

        if self.portfolio_values.ndim != 2:
            raise ValueError(
                "portfolio_values must have dimensions "
                "[path, time]."
            )

        if (
            self.trade_values.shape[0]
            !=
            self.portfolio_values.shape[0]
        ):
            raise ValueError(
                "Trade and portfolio path counts differ."
            )

        if (
            self.trade_values.shape[1]
            !=
            self.portfolio_values.shape[1]
        ):
            raise ValueError(
                "Trade and portfolio time dimensions differ."
            )

        if (
            self.trade_values.shape[1]
            !=
            len(
                self.exposure_times
            )
        ):
            raise ValueError(
                "Exposure-time dimension is inconsistent."
            )

        if (
            self.trade_values.shape[2]
            !=
            len(
                self.trade_ids
            )
        ):
            raise ValueError(
                "Trade-id dimension is inconsistent."
            )

    def number_of_paths(
        self
    ):
        """
        Return the number of Monte Carlo paths.
        """

        return self.portfolio_values.shape[0]

    def number_of_times(
        self
    ):
        """
        Return the number of exposure dates.
        """

        return self.portfolio_values.shape[1]

    def number_of_trades(
        self
    ):
        """
        Return the number of trades.
        """

        return self.trade_values.shape[2]


def exact_time_index(
    times,
    target_time,
    tolerance=1.0e-10
):
    """
    Locate an exact time on a simulation or tenor grid.
    """

    times = np.asarray(
        times,
        dtype=float
    )

    differences = np.abs(
        times
        -
        float(
            target_time
        )
    )

    matching_indices = np.where(
        differences
        <=
        tolerance
    )[0]

    if len(
        matching_indices
    ) == 0:
        raise ValueError(
            f"Time {target_time} is not present on the grid."
        )

    return int(
        matching_indices[0]
    )


def get_tenor_times(
    model
):
    """
    Extract tenor times from a Chapter 13 or Chapter 14 model.
    """

    if hasattr(
        model,
        "tenor"
    ):
        tenor = model.tenor

    elif hasattr(
        model,
        "tenor_structure"
    ):
        tenor = model.tenor_structure

    else:
        raise AttributeError(
            "The model must contain tenor or tenor_structure."
        )

    if not hasattr(
        tenor,
        "times"
    ):
        raise AttributeError(
            "The tenor object must contain times."
        )

    return np.asarray(
        tenor.times,
        dtype=float
    )


def get_accruals(
    model
):
    """
    Extract accrual periods from the model tenor.
    """

    if hasattr(
        model,
        "tenor"
    ):
        tenor = model.tenor

    elif hasattr(
        model,
        "tenor_structure"
    ):
        tenor = model.tenor_structure

    else:
        raise AttributeError(
            "The model must contain tenor or tenor_structure."
        )

    if hasattr(
        tenor,
        "accruals"
    ):
        accruals = tenor.accruals

    elif hasattr(
        tenor,
        "year_fractions"
    ):
        accruals = tenor.year_fractions

    else:
        tenor_times = np.asarray(
            tenor.times,
            dtype=float
        )

        accruals = np.diff(
            tenor_times
        )

    return np.asarray(
        accruals,
        dtype=float
    )


def bond_prices_from_forwards(
    forwards,
    accruals,
    current_tenor_index
):
    """
    Reconstruct discount factors from the current tenor date.

    The returned array has one value for every tenor date.

    Values before current_tenor_index are NaN because they
    represent already-past discount factors.
    """

    forwards = np.asarray(
        forwards,
        dtype=float
    )

    accruals = np.asarray(
        accruals,
        dtype=float
    )

    number_of_forwards = len(
        forwards
    )

    if len(
        accruals
    ) != number_of_forwards:
        raise ValueError(
            "forwards and accruals must have equal length."
        )

    if (
        current_tenor_index < 0
        or
        current_tenor_index > number_of_forwards
    ):
        raise IndexError(
            "Invalid current_tenor_index."
        )

    bonds = np.full(
        number_of_forwards + 1,
        np.nan,
        dtype=float
    )

    bonds[
        current_tenor_index
    ] = 1.0

    for forward_index in range(
        current_tenor_index,
        number_of_forwards
    ):
        denominator = (
            1.0
            +
            accruals[
                forward_index
            ]
            *
            forwards[
                forward_index
            ]
        )

        if denominator <= 0.0:
            raise RuntimeError(
                "Invalid forward curve: "
                "1 + delta * L must be positive."
            )

        bonds[
            forward_index + 1
        ] = (
            bonds[
                forward_index
            ]
            /
            denominator
        )

    return bonds


def value_interest_rate_swap(
    trade,
    valuation_time,
    forwards,
    model
):
    """
    Value one vanilla swap at a tenor-aligned valuation time.

    The valuation is performed at tenor dates. If the swap
    has already started, the floating leg is approximated
    from the current reset date to maturity.

    The returned value is from the holder's perspective.
    """

    if not isinstance(
        trade,
        InterestRateSwap
    ):
        raise TypeError(
            "trade must be an InterestRateSwap."
        )

    valuation_time = float(
        valuation_time
    )

    if valuation_time >= trade.end_time:
        return 0.0

    tenor_times = get_tenor_times(
        model
    )

    accruals = get_accruals(
        model
    )

    current_index = exact_time_index(
        tenor_times,
        valuation_time
    )

    swap_start_index = exact_time_index(
        tenor_times,
        trade.start_time
    )

    swap_end_index = exact_time_index(
        tenor_times,
        trade.end_time
    )

    effective_start_index = max(
        current_index,
        swap_start_index
    )

    bonds = bond_prices_from_forwards(
        forwards=forwards,
        accruals=accruals,
        current_tenor_index=current_index
    )

    start_bond = bonds[
        effective_start_index
    ]

    end_bond = bonds[
        swap_end_index
    ]

    floating_leg = (
        start_bond
        -
        end_bond
    )

    fixed_leg_annuity = 0.0

    for payment_index in range(
        effective_start_index,
        swap_end_index
    ):
        fixed_leg_annuity += (
            accruals[
                payment_index
            ]
            *
            bonds[
                payment_index + 1
            ]
        )

    fixed_leg = (
        trade.fixed_rate
        *
        fixed_leg_annuity
    )

    payer_fixed_value = (
        trade.notional
        *
        (
            floating_leg
            -
            fixed_leg
        )
    )

    return (
        trade.direction()
        *
        payer_fixed_value
    )


def build_exposure_times(
    model,
    simulation,
    final_time=None
):
    """
    Build exposure dates that are present on both the tenor
    grid and the Monte Carlo simulation grid.
    """

    tenor_times = get_tenor_times(
        model
    )

    simulation_times = np.asarray(
        simulation.times,
        dtype=float
    )

    if final_time is None:
        final_time = min(
            tenor_times[-1],
            simulation_times[-1]
        )

    exposure_times = []

    for tenor_time in tenor_times:
        if tenor_time > final_time + 1.0e-12:
            continue

        differences = np.abs(
            simulation_times
            -
            tenor_time
        )

        if np.min(
            differences
        ) <= 1.0e-10:
            exposure_times.append(
                tenor_time
            )

    if not exposure_times:
        raise RuntimeError(
            "No common exposure dates were found."
        )

    return np.asarray(
        exposure_times,
        dtype=float
    )


def simulate_portfolio_values(
    model,
    simulation,
    netting_set,
    exposure_times=None
):
    """
    Revalue all trades across all paths and exposure dates.

    Parameters
    ----------
    model
        Chapter 13 Gaussian LMM or Chapter 14 LMM-SABR model.

    simulation
        Simulation result containing times and forward_paths.

    netting_set
        NettingSet containing vanilla interest-rate swaps.

    exposure_times
        Optional tenor-aligned exposure dates.

    Returns
    -------
    ExposureSimulationResult
    """

    if not isinstance(
        netting_set,
        NettingSet
    ):
        raise TypeError(
            "netting_set must be a NettingSet."
        )

    if exposure_times is None:
        exposure_times = build_exposure_times(
            model=model,
            simulation=simulation,
            final_time=netting_set.maturity()
        )

    exposure_times = np.asarray(
        exposure_times,
        dtype=float
    )

    number_of_paths = (
        simulation.forward_paths.shape[0]
    )

    number_of_times = len(
        exposure_times
    )

    number_of_trades = (
        netting_set.number_of_trades()
    )

    trade_values = np.zeros(
        (
            number_of_paths,
            number_of_times,
            number_of_trades
        ),
        dtype=float
    )

    for time_position, exposure_time in enumerate(
        exposure_times
    ):
        simulation_time_index = exact_time_index(
            simulation.times,
            exposure_time
        )

        forwards_at_time = (
            simulation.forward_paths[
                :,
                simulation_time_index,
                :
            ]
        )

        for path_index in range(
            number_of_paths
        ):
            path_forwards = forwards_at_time[
                path_index
            ]

            for trade_index, trade in enumerate(
                netting_set.trades
            ):
                trade_values[
                    path_index,
                    time_position,
                    trade_index
                ] = value_interest_rate_swap(
                    trade=trade,
                    valuation_time=exposure_time,
                    forwards=path_forwards,
                    model=model
                )

    portfolio_values = np.sum(
        trade_values,
        axis=2
    )

    trade_ids = [
        trade.trade_id
        for trade in netting_set.trades
    ]

    return ExposureSimulationResult(
        exposure_times=exposure_times,
        trade_ids=trade_ids,
        trade_values=trade_values,
        portfolio_values=portfolio_values
    )