#include <iostream>
#include <vector>
#include <iomanip>

#include "../../06_black_swaption_pricing/cpp/curve.hpp"

#include "VolSurface.hpp"
#include "SwaptionPriceSurface.hpp"
#include "DupireBuilder.hpp"
#include "LocalVolSurface.hpp"

int main(){

    /*
        1. Build yield curve

        This should match Chapter 07 curve_data.csv.
    */

    std::vector<double> maturities =
    {
        0.5, 1.0, 2.0, 3.0, 5.0,
        7.0, 10.0, 15.0, 20.0, 30.0
    };

    std::vector<double> zeroRates =
    {
        0.0435, 0.0440, 0.0438, 0.0432, 0.0425,
        0.0421, 0.0418, 0.0416, 0.0415, 0.0414
    };

    YieldCurve curve(
        maturities,
        zeroRates
    );

    /*
        2. Build clean common strike grid

        In Python this is generated by build_common_strike_grid().
        Here we hardcode a representative common grid.
    */

    std::vector<double> expiries =
    {
        1.0, 2.0, 3.0, 5.0, 7.0, 10.0
    };

    std::vector<double> strikes =
    {0.02245276, 0.03222231, 0.04199186, 0.05176141, 0.06153096};

    /*
        3. Black implied vol matrix

        Decimal vols.
        Example:
        0.0022 = 22bp Black vol.
    */

    std::vector<std::vector<double>> vols =
    {
        {0.0081,     0.00761152, 0.00721844, 0.00738617, 0.00785391},
        {0.00827119, 0.00778617, 0.0074023,  0.0075977,  0.00808272},
        {0.00946339, 0.0088796,  0.00660542, 0.00680612, 0.00827155},
        {0.01485391, 0.01430321, 0.01300922, 0.01321152, 0.0137},
        {0.02010771, 0.01905132, 0.01830756, 0.01850738, 0.01899586},
        {0.02455907, 0.02401767, 0.02270715, 0.02290636, 0.02339484}
    };

    VolSurface volSurface(
        expiries,
        strikes,
        vols
    );

    /*
        4. Build swaption price surface
    */

    SwaptionPriceSurface priceSurface(
        &curve,
        &volSurface,
        5.0,
        1.0,
        true
    );

    priceSurface.build();

    std::cout
        << "Swaption price surface built."
        << std::endl;

    /*
        5. Build Dupire local vol surface
    */

    DupireBuilder dupire(
        &priceSurface
    );

    LocalVolSurface localSurface =
        dupire.build();

    std::cout
        << "Dupire local vol surface built."
        << std::endl;

    /*
        6. Print local vol matrix
    */

    std::cout
        << std::fixed
        << std::setprecision(6);

    for(size_t i = 0; i < localSurface.expiries.size(); ++i){

        for(size_t j = 0; j < localSurface.strikes.size(); ++j){

            std::cout
                << localSurface.localVols[i][j]
                << " ";
        }

        std::cout << std::endl;
    }

    /*
        7. Interpolate one interior local vol point
    */

    try {

        double lv =
            localSurface.getLocalVol(
                4.0,
                0.0468766
            );

        std::cout
            << "Interpolated local vol at expiry=4Y, strike=4.69%: "
            << lv
            << std::endl;

    } catch(const std::exception& e){

        std::cout
            << "Interpolation failed: "
            << e.what()
            << std::endl;
    }

    return 0;
}
